apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokulreact-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gokulreact
  template:
    metadata:
      labels:
        app: gokulreact
    spec:
      containers:
        - name: gokulreact
          image: padidaparama/gokulreact:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gokulreact-sev
spec:
  selector:
    app: gokulreact
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
