name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Build NPM Project
        run: |
          npm install
          npm run build
          
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          registry: "docker.io"
          username: "padidaparama"
          password: "9345746516"
      
      - name: Build image and push
        run: |
          export SHELL=/bin/bash
          #eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t gokulreact:v1 .
          echo -n "verifying images:"
          docker images
          docker tag gokulreact:v1 padidaparama/gokulreact:v1
          docker push padidaparama/gokulreact:v1
          
#      - name: Docker push
#        run: |
#          docker push kaninipro/gokulreact:v1
         
          
          
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
          
#      - name: Deploy to EKS
#        run: |
#          kubectl apply -f deployment.yaml
          
          
 #     - name: Test service URLs
 #       run: |
 #         kubectl get all -o wide
 #         kubectl get svc
 #         kubectl service gokulreact-service --url
      
#      - name: Docker Login
#        uses: docker/login-action@v2.2.0
#        with:
#          registry: your-docker-registry.com
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
          
      
#      - name: Push Docker Image
#        run: |
#          docker push gokulreact:v1
      
#      - name: Deploy to EKS
#        run: |
#          ansible-playbook -i inventory.ini playbook.yml -e "image_name=your-image-name" -e "ansible_user=$ANSIBLE_USER" -e "ansible_pass=$ANSIBLE_PASS"
